var mock_data={}
function setData(mapper_count=0){
    mock_data={
        "meta": {
          "success": true,
          "message": "Added into file",
          "info": null
        },
        "data": {
          "api_key": "bih4DycWYMU9iXUXh8TLTWXb5IuD2-Ph",
          "start_date": "2006-01-02T20:34:05+05:30",
          "end_date": "2006-01-02T20:34:05+05:30",
          "plan_id": 2,
          "plan_details": {
            "id": 2,
            "App": null,
            "name": "subscription2",
            "price": 600,
            "usage": {
              "mapper": mapper_count,
              "catalogue": 0
            },
            "app_id": null,
            "tenure": 2,
            "services": [
              {
                "id": 3,
                "App": null,
                "rules": {
                  "catalogue": 1000
                },
                "app_id": null,
                "service": {
                  "ID": 850,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": true,
                  "description": "",
                  "lookup_code": "CATELOGUE",
                  "source_code": "",
                  "display_name": "Catelogue",
                  "lookup_type_id": 159
                },
                "CreatedBy": {
                  "id": 11,
                  "auth": {},
                  "name": "Super User",
                  "email": "",
                  "company": {
                    "id": 0,
                    "name": "",
                    "type": null,
                    "email": "",
                    "gstin": "",
                    "phone": "",
                    "website": "",
                    "fssai_no": "",
                    "holidays": null,
                    "CreatedBy": null,
                    "UpdatedBy": null,
                    "child_ids": null,
                    "is_active": false,
                    "parent_id": 0,
                    "created_by": null,
                    "is_enabled": null,
                    "pan_number": "",
                    "schedulers": null,
                    "updated_by": null,
                    "api_version": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "constraints": null,
                    "provider_id": "",
                    "bank_details": {
                      "city": "",
                      "state": "",
                      "bank_name": "",
                      "ifsc_code": "",
                      "branch_name": "",
                      "holder_name": "",
                      "upi_address": "",
                      "account_number": "",
                      "bank_statement": null,
                      "cancelled_cheque": null,
                      "ondc_settlement_type": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "ondc_settlement_type_id": null,
                      "penny_transfer_verification": false
                    },
                    "company_type": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "created_date": "0001-01-01T00:00:00Z",
                    "is_enterpise": false,
                    "ondc_details": {
                      "id": null,
                      "type": null,
                      "collector": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "unique_id": "",
                      "cache_search": null,
                      "collector_id": null,
                      "created_date": "0001-01-01T00:00:00Z",
                      "is_collector": false,
                      "updated_date": "0001-01-01T00:00:00Z",
                      "subscriber_id": "",
                      "subscriber_url": "",
                      "signing_public_key": "",
                      "signing_private_key": "",
                      "encryption_public_key": "",
                      "encryption_private_key": "",
                      "buyer_app_finder_fee_type": "",
                      "buyer_app_finder_fee_amount": ""
                    },
                    "ondc_version": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "rating_count": 0,
                    "total_points": 0,
                    "updated_date": "0001-01-01T00:00:00Z",
                    "business_type": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "delivery_type": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "kyc_documents": null,
                    "plt_point_ids": null,
                    "signature_url": "",
                    "aadhaar_number": "",
                    "api_version_id": null,
                    "menu_hierarchy": null,
                    "queue_services": null,
                    "rating_average": 0,
                    "company_details": {
                      "domain": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "std_code": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "domain_id": null,
                      "store_name": "",
                      "seller_apps": null,
                      "std_code_id": null,
                      "business_name": "",
                      "store_timings": null,
                      "established_on": "0001-01-01T00:00:00Z",
                      "business_address": "",
                      "serviceable_areas": null,
                      "store_description": "",
                      "financial_year_end": "0001-01-01T00:00:00Z",
                      "authorised_signatory": "",
                      "financial_year_start": "0001-01-01T00:00:00Z",
                      "enable_email_notifications": false,
                      "enable_phone_notifications": false,
                      "authorised_signatory_address": ""
                    },
                    "file_preference": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "ondc_details_id": null,
                    "ondc_version_id": null,
                    "otp_preferences": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "business_type_id": null,
                    "company_defaults": null,
                    "delivery_type_id": null,
                    "otp_preference_id": null,
                    "file_preference_id": null,
                    "invoice_generation": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "language_preferred": "",
                    "product_fulfillment": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "shipping_preference": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "NotificationSettings": {
                      "id": 0,
                      "name": "",
                      "email_pop": null,
                      "email_smtp": null,
                      "email_domain": "",
                      "sms_settings": null,
                      "pixel_settings": null,
                      "branch_settings": null,
                      "hotjar_settings": null,
                      "firebase_settings": null,
                      "app_header_settings": null,
                      "apps_flyer_settings": null,
                      "mobile_push_settings": null,
                      "tag_manager_settings": null,
                      "third_party_settings": null,
                      "browser_notifications": null
                    },
                    "delivery_preferences": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "time_slots_preferred": "",
                    "invoice_generation_id": null,
                    "lsp_partner_preference": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "product_fulfillment_id": null,
                    "shipping_preference_id": null,
                    "working_hours_end_time": "0001-01-01T00:00:00Z",
                    "delivery_preferences_id": null,
                    "notification_preferences": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "notification_settings_id": null,
                    "notification_template_id": null,
                    "working_hours_start_time": "0001-01-01T00:00:00Z",
                    "lsp_partner_preference_id": null,
                    "notification_preference_id": null
                  },
                  "profile": {},
                  "role_id": null,
                  "2fa_conf": [],
                  "password": "",
                  "username": "super_user@eunimart.com",
                  "CreatedBy": null,
                  "UpdatedBy": null,
                  "is_active": true,
                  "last_name": "User",
                  "tutorials": [],
                  "access_ids": [
                    1
                  ],
                  "company_id": 1,
                  "created_by": null,
                  "device_ids": [],
                  "first_name": "Super",
                  "is_enabled": true,
                  "login_type": 0,
                  "schedulers": [],
                  "updated_by": null,
                  "user_types": [
                    {
                      "id": 634,
                      "name": "SELLER"
                    }
                  ],
                  "work_email": "",
                  "constraints": [],
                  "preferences": [],
                  "created_date": "0001-01-01T00:00:00Z",
                  "gamification": [],
                  "plt_point_id": null,
                  "total_points": 0,
                  "updated_date": "0001-01-01T00:00:00Z",
                  "mobile_number": "",
                  "menu_hierarchy": {
                    "otp_token": "666666"
                  },
                  "queue_services": [],
                  "external_details": {},
                  "access_template_id": null
                },
                "DeletedBy": null,
                "UpdatedBy": null,
                "is_active": true,
                "company_id": 1,
                "created_by": 11,
                "deleted_by": null,
                "is_enabled": true,
                "service_id": 850,
                "updated_by": null,
                "created_date": "2023-06-14T19:27:02.193482+05:30",
                "type_of_rule": {
                  "ID": 852,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": true,
                  "description": "",
                  "lookup_code": "FULL_USAGE",
                  "source_code": "",
                  "display_name": "Full Usage",
                  "lookup_type_id": 160
                },
                "updated_date": "2023-06-14T19:27:02.193482+05:30",
                "type_of_rule_id": 852
              },
              {
                "id": 4,
                "App": null,
                "rules": {
                  "mapper": 2
                },
                "app_id": null,
                "service": {
                  "ID": 850,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": true,
                  "description": "",
                  "lookup_code": "CATELOGUE",
                  "source_code": "",
                  "display_name": "Catelogue",
                  "lookup_type_id": 159
                },
                "CreatedBy": {
                  "id": 11,
                  "auth": {},
                  "name": "Super User",
                  "email": "",
                  "company": {
                    "id": 0,
                    "name": "",
                    "type": null,
                    "email": "",
                    "gstin": "",
                    "phone": "",
                    "website": "",
                    "fssai_no": "",
                    "holidays": null,
                    "CreatedBy": null,
                    "UpdatedBy": null,
                    "child_ids": null,
                    "is_active": false,
                    "parent_id": 0,
                    "created_by": null,
                    "is_enabled": null,
                    "pan_number": "",
                    "schedulers": null,
                    "updated_by": null,
                    "api_version": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "constraints": null,
                    "provider_id": "",
                    "bank_details": {
                      "city": "",
                      "state": "",
                      "bank_name": "",
                      "ifsc_code": "",
                      "branch_name": "",
                      "holder_name": "",
                      "upi_address": "",
                      "account_number": "",
                      "bank_statement": null,
                      "cancelled_cheque": null,
                      "ondc_settlement_type": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "ondc_settlement_type_id": null,
                      "penny_transfer_verification": false
                    },
                    "company_type": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "created_date": "0001-01-01T00:00:00Z",
                    "is_enterpise": false,
                    "ondc_details": {
                      "id": null,
                      "type": null,
                      "collector": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "unique_id": "",
                      "cache_search": null,
                      "collector_id": null,
                      "created_date": "0001-01-01T00:00:00Z",
                      "is_collector": false,
                      "updated_date": "0001-01-01T00:00:00Z",
                      "subscriber_id": "",
                      "subscriber_url": "",
                      "signing_public_key": "",
                      "signing_private_key": "",
                      "encryption_public_key": "",
                      "encryption_private_key": "",
                      "buyer_app_finder_fee_type": "",
                      "buyer_app_finder_fee_amount": ""
                    },
                    "ondc_version": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "rating_count": 0,
                    "total_points": 0,
                    "updated_date": "0001-01-01T00:00:00Z",
                    "business_type": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "delivery_type": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "kyc_documents": null,
                    "plt_point_ids": null,
                    "signature_url": "",
                    "aadhaar_number": "",
                    "api_version_id": null,
                    "menu_hierarchy": null,
                    "queue_services": null,
                    "rating_average": 0,
                    "company_details": {
                      "domain": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "std_code": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "LookupType": {
                          "ID": 0,
                          "CreatedAt": "0001-01-01T00:00:00Z",
                          "DeletedAt": null,
                          "UpdatedAt": "0001-01-01T00:00:00Z",
                          "is_enabled": null,
                          "Lookupcodes": null,
                          "lookup_type": "",
                          "display_name": ""
                        },
                        "is_enabled": null,
                        "description": "",
                        "lookup_code": "",
                        "source_code": "",
                        "display_name": "",
                        "lookup_type_id": 0
                      },
                      "domain_id": null,
                      "store_name": "",
                      "seller_apps": null,
                      "std_code_id": null,
                      "business_name": "",
                      "store_timings": null,
                      "established_on": "0001-01-01T00:00:00Z",
                      "business_address": "",
                      "serviceable_areas": null,
                      "store_description": "",
                      "financial_year_end": "0001-01-01T00:00:00Z",
                      "authorised_signatory": "",
                      "financial_year_start": "0001-01-01T00:00:00Z",
                      "enable_email_notifications": false,
                      "enable_phone_notifications": false,
                      "authorised_signatory_address": ""
                    },
                    "file_preference": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "ondc_details_id": null,
                    "ondc_version_id": null,
                    "otp_preferences": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "business_type_id": null,
                    "company_defaults": null,
                    "delivery_type_id": null,
                    "otp_preference_id": null,
                    "file_preference_id": null,
                    "invoice_generation": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "language_preferred": "",
                    "product_fulfillment": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "shipping_preference": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "NotificationSettings": {
                      "id": 0,
                      "name": "",
                      "email_pop": null,
                      "email_smtp": null,
                      "email_domain": "",
                      "sms_settings": null,
                      "pixel_settings": null,
                      "branch_settings": null,
                      "hotjar_settings": null,
                      "firebase_settings": null,
                      "app_header_settings": null,
                      "apps_flyer_settings": null,
                      "mobile_push_settings": null,
                      "tag_manager_settings": null,
                      "third_party_settings": null,
                      "browser_notifications": null
                    },
                    "delivery_preferences": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "time_slots_preferred": "",
                    "invoice_generation_id": null,
                    "lsp_partner_preference": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "product_fulfillment_id": null,
                    "shipping_preference_id": null,
                    "working_hours_end_time": "0001-01-01T00:00:00Z",
                    "delivery_preferences_id": null,
                    "notification_preferences": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "LookupType": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "is_enabled": null,
                        "Lookupcodes": null,
                        "lookup_type": "",
                        "display_name": ""
                      },
                      "is_enabled": null,
                      "description": "",
                      "lookup_code": "",
                      "source_code": "",
                      "display_name": "",
                      "lookup_type_id": 0
                    },
                    "notification_settings_id": null,
                    "notification_template_id": null,
                    "working_hours_start_time": "0001-01-01T00:00:00Z",
                    "lsp_partner_preference_id": null,
                    "notification_preference_id": null
                  },
                  "profile": {},
                  "role_id": null,
                  "2fa_conf": [],
                  "password": "",
                  "username": "super_user@eunimart.com",
                  "CreatedBy": null,
                  "UpdatedBy": null,
                  "is_active": true,
                  "last_name": "User",
                  "tutorials": [],
                  "access_ids": [
                    1
                  ],
                  "company_id": 1,
                  "created_by": null,
                  "device_ids": [],
                  "first_name": "Super",
                  "is_enabled": true,
                  "login_type": 0,
                  "schedulers": [],
                  "updated_by": null,
                  "user_types": [
                    {
                      "id": 634,
                      "name": "SELLER"
                    }
                  ],
                  "work_email": "",
                  "constraints": [],
                  "preferences": [],
                  "created_date": "0001-01-01T00:00:00Z",
                  "gamification": [],
                  "plt_point_id": null,
                  "total_points": 0,
                  "updated_date": "0001-01-01T00:00:00Z",
                  "mobile_number": "",
                  "menu_hierarchy": {
                    "otp_token": "666666"
                  },
                  "queue_services": [],
                  "external_details": {},
                  "access_template_id": null
                },
                "DeletedBy": null,
                "UpdatedBy": null,
                "is_active": true,
                "company_id": 1,
                "created_by": 11,
                "deleted_by": null,
                "is_enabled": true,
                "service_id": 850,
                "updated_by": null,
                "created_date": "2023-06-14T19:28:01.240617+05:30",
                "type_of_rule": {
                  "ID": 853,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": true,
                  "description": "",
                  "lookup_code": "USAGE_COUNTER",
                  "source_code": "",
                  "display_name": "Usage Counter",
                  "lookup_type_id": 160
                },
                "updated_date": "2023-06-14T19:28:01.240617+05:30",
                "type_of_rule_id": 853
              }
            ],
            "CreatedBy": {
              "id": 11,
              "auth": {},
              "name": "Super User",
              "email": "",
              "company": {
                "id": 0,
                "name": "",
                "type": null,
                "email": "",
                "gstin": "",
                "phone": "",
                "website": "",
                "fssai_no": "",
                "holidays": null,
                "CreatedBy": null,
                "UpdatedBy": null,
                "child_ids": null,
                "is_active": false,
                "parent_id": 0,
                "created_by": null,
                "is_enabled": null,
                "pan_number": "",
                "schedulers": null,
                "updated_by": null,
                "api_version": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "constraints": null,
                "provider_id": "",
                "bank_details": {
                  "city": "",
                  "state": "",
                  "bank_name": "",
                  "ifsc_code": "",
                  "branch_name": "",
                  "holder_name": "",
                  "upi_address": "",
                  "account_number": "",
                  "bank_statement": null,
                  "cancelled_cheque": null,
                  "ondc_settlement_type": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "LookupType": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "is_enabled": null,
                      "Lookupcodes": null,
                      "lookup_type": "",
                      "display_name": ""
                    },
                    "is_enabled": null,
                    "description": "",
                    "lookup_code": "",
                    "source_code": "",
                    "display_name": "",
                    "lookup_type_id": 0
                  },
                  "ondc_settlement_type_id": null,
                  "penny_transfer_verification": false
                },
                "company_type": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "created_date": "0001-01-01T00:00:00Z",
                "is_enterpise": false,
                "ondc_details": {
                  "id": null,
                  "type": null,
                  "collector": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "LookupType": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "is_enabled": null,
                      "Lookupcodes": null,
                      "lookup_type": "",
                      "display_name": ""
                    },
                    "is_enabled": null,
                    "description": "",
                    "lookup_code": "",
                    "source_code": "",
                    "display_name": "",
                    "lookup_type_id": 0
                  },
                  "unique_id": "",
                  "cache_search": null,
                  "collector_id": null,
                  "created_date": "0001-01-01T00:00:00Z",
                  "is_collector": false,
                  "updated_date": "0001-01-01T00:00:00Z",
                  "subscriber_id": "",
                  "subscriber_url": "",
                  "signing_public_key": "",
                  "signing_private_key": "",
                  "encryption_public_key": "",
                  "encryption_private_key": "",
                  "buyer_app_finder_fee_type": "",
                  "buyer_app_finder_fee_amount": ""
                },
                "ondc_version": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "rating_count": 0,
                "total_points": 0,
                "updated_date": "0001-01-01T00:00:00Z",
                "business_type": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "delivery_type": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "kyc_documents": null,
                "plt_point_ids": null,
                "signature_url": "",
                "aadhaar_number": "",
                "api_version_id": null,
                "menu_hierarchy": null,
                "queue_services": null,
                "rating_average": 0,
                "company_details": {
                  "domain": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "LookupType": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "is_enabled": null,
                      "Lookupcodes": null,
                      "lookup_type": "",
                      "display_name": ""
                    },
                    "is_enabled": null,
                    "description": "",
                    "lookup_code": "",
                    "source_code": "",
                    "display_name": "",
                    "lookup_type_id": 0
                  },
                  "std_code": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "LookupType": {
                      "ID": 0,
                      "CreatedAt": "0001-01-01T00:00:00Z",
                      "DeletedAt": null,
                      "UpdatedAt": "0001-01-01T00:00:00Z",
                      "is_enabled": null,
                      "Lookupcodes": null,
                      "lookup_type": "",
                      "display_name": ""
                    },
                    "is_enabled": null,
                    "description": "",
                    "lookup_code": "",
                    "source_code": "",
                    "display_name": "",
                    "lookup_type_id": 0
                  },
                  "domain_id": null,
                  "store_name": "",
                  "seller_apps": null,
                  "std_code_id": null,
                  "business_name": "",
                  "store_timings": null,
                  "established_on": "0001-01-01T00:00:00Z",
                  "business_address": "",
                  "serviceable_areas": null,
                  "store_description": "",
                  "financial_year_end": "0001-01-01T00:00:00Z",
                  "authorised_signatory": "",
                  "financial_year_start": "0001-01-01T00:00:00Z",
                  "enable_email_notifications": false,
                  "enable_phone_notifications": false,
                  "authorised_signatory_address": ""
                },
                "file_preference": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "ondc_details_id": null,
                "ondc_version_id": null,
                "otp_preferences": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "business_type_id": null,
                "company_defaults": null,
                "delivery_type_id": null,
                "otp_preference_id": null,
                "file_preference_id": null,
                "invoice_generation": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "language_preferred": "",
                "product_fulfillment": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "shipping_preference": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "NotificationSettings": {
                  "id": 0,
                  "name": "",
                  "email_pop": null,
                  "email_smtp": null,
                  "email_domain": "",
                  "sms_settings": null,
                  "pixel_settings": null,
                  "branch_settings": null,
                  "hotjar_settings": null,
                  "firebase_settings": null,
                  "app_header_settings": null,
                  "apps_flyer_settings": null,
                  "mobile_push_settings": null,
                  "tag_manager_settings": null,
                  "third_party_settings": null,
                  "browser_notifications": null
                },
                "delivery_preferences": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "time_slots_preferred": "",
                "invoice_generation_id": null,
                "lsp_partner_preference": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "product_fulfillment_id": null,
                "shipping_preference_id": null,
                "working_hours_end_time": "0001-01-01T00:00:00Z",
                "delivery_preferences_id": null,
                "notification_preferences": {
                  "ID": 0,
                  "CreatedAt": "0001-01-01T00:00:00Z",
                  "DeletedAt": null,
                  "UpdatedAt": "0001-01-01T00:00:00Z",
                  "LookupType": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "is_enabled": null,
                    "Lookupcodes": null,
                    "lookup_type": "",
                    "display_name": ""
                  },
                  "is_enabled": null,
                  "description": "",
                  "lookup_code": "",
                  "source_code": "",
                  "display_name": "",
                  "lookup_type_id": 0
                },
                "notification_settings_id": null,
                "notification_template_id": null,
                "working_hours_start_time": "0001-01-01T00:00:00Z",
                "lsp_partner_preference_id": null,
                "notification_preference_id": null
              },
              "profile": {},
              "role_id": null,
              "2fa_conf": [],
              "password": "",
              "username": "super_user@eunimart.com",
              "CreatedBy": null,
              "UpdatedBy": null,
              "is_active": true,
              "last_name": "User",
              "tutorials": [],
              "access_ids": [
                1
              ],
              "company_id": 1,
              "created_by": null,
              "device_ids": [],
              "first_name": "Super",
              "is_enabled": true,
              "login_type": 0,
              "schedulers": [],
              "updated_by": null,
              "user_types": [
                {
                  "id": 634,
                  "name": "SELLER"
                }
              ],
              "work_email": "",
              "constraints": [],
              "preferences": [],
              "created_date": "0001-01-01T00:00:00Z",
              "gamification": [],
              "plt_point_id": null,
              "total_points": 0,
              "updated_date": "0001-01-01T00:00:00Z",
              "mobile_number": "",
              "menu_hierarchy": {
                "otp_token": "666666"
              },
              "queue_services": [],
              "external_details": {},
              "access_template_id": null
            },
            "DeletedBy": null,
            "UpdatedBy": null,
            "is_active": true,
            "assigne_to": null,
            "company_id": 1,
            "created_by": 11,
            "deleted_by": null,
            "is_enabled": true,
            "updated_by": null,
            "services_id": [
              3,
              4
            ],
            "created_date": "2023-06-14T19:33:46.066645+05:30",
            "updated_date": "2023-06-14T19:33:46.066645+05:30"
          }
        },
        "is_valid":true
      }
    }
function getData(){
    return mock_data
}

export {setData,getData}


//   sdk.emitter.on("seller_search", function (data) {
//     sdk.order.Search(
//       {
//         "name": "search",
//         "http_entity_endpoint": "http://localhost:8081/temp_data",
//         "http_timeout": 8000,
//         "http_retry_count": 0,
//         "header_validity": 600000,
//         "header_authentication": true,
//         "set_authorization_header": true
//       },
//       {
//         "bpp_descriptor": {
//           "name": "bpp_descriptor.name",
//           "symbol": "bpp_descriptor.symbol",
//           "short_desc": "bpp_descriptor.short_desc",
//           "long_desc": "bpp_descriptor.long_desc",
//           "images": "bpp_descriptor.images"
//         },
//         "bpp_providers": [
//           {
//             "id": "bpp_providers.id",
//             "time": "bpp_providers.time",
//             "descriptor": "bpp_providers.descriptor",
//             "@ondc/org/fssai_license_no": "bpp_providers.fssai_license_no",
//             "ttl": "bpp_providers.ttl",
//             "locations": [
//               {
//                 "id": "bpp_providers.locations.id",
//                 "gps": "bpp_providers.locations.gps",
//                 "address": "bpp_providers.locations.address",
//                 "circle": {
//                   "gps": "bpp_providers.locations.circle.gps",
//                   "radius": "bpp_providers.locations.circle.radius"
//                 },
//                 "time": {
//                   "days": "bpp_providers.locations.time.days",
//                   "schedule": "bpp_providers.locations.time.schedule",
//                   "range": "bpp_providers.locations.time.range"
//                 }
//               }
//             ],
//             "items": [
//               {
//                 "id": "bpp_providers.items.id",
//                 "descriptor": "bpp_providers.items.descriptor",
//                 "quantity_available": "bpp_providers.items.quantity.available.count",
//                 "quantity_maximum": "bpp_providers.items.quantity.maximum.count",
//                 "price": "bpp_providers.items.price",
//                 "category_id": "bpp_providers.items.category_id",
//                 "fulfillment_id": "bpp_providers.items.fulfillment_id",
//                 "location_id": "bpp_providers.items.location_id",
//                 "recommended": "bpp_providers.items.recommended",
//                 "@ondc/org/returnable": "bpp_providers.items.returnable",
//                 "@ondc/org/cancellable": "bpp_providers.items.cancellable",
//                 "@ondc/org/return_window": "bpp_providers.items.return_window",
//                 "@ondc/org/seller_pickup_return": "bpp_providers.items.seller_pickup_return",
//                 "@ondc/org/time_to_ship": "bpp_providers.items.time_to_ship",
//                 "@ondc/org/available_on_cod": "bpp_providers.items.available_on_cod",
//                 "@ondc/org/contact_details_consumer_care": "bpp_providers.items.contact_details_consumer_care",
//                 "tags": "bpp_providers.items.tags",
//                 "test": "bpp_providers.items.time_to_ship",
//                 "@ondc/org/statutory_reqs_packaged_commodities": {
//                   "manufacturer_or_packer_name": "bpp_providers.items.time_to_ship",
//                   "manufacturer_or_packer_address": "bpp_providers.items.time_to_ship",
//                   "common_or_generic_name_of_commodity": "bpp_providers.items.time_to_ship",
//                   "net_quantity_or_measure_of_commodity_in_pkg": "bpp_providers.items.time_to_ship",
//                   "month_year_of_manufacture_packing_import": "bpp_providers.items.time_to_ship",
//                   "imported_product_country_of_origin": "bpp_providers.items.time_to_ship"
//                 },
//                 "@ondc/org/statutory_reqs_prepackaged_food": {
//                   "nutritional_info": "bpp_providers.items.time_to_ship",
//                   "additives_info": "bpp_providers.items.time_to_ship",
//                   "brand_owner_FSSAI_license_no": "bpp_providers.items.time_to_ship",
//                   "other_FSSAI_license_no": "bpp_providers.items.time_to_ship",
//                   "importer_FSSAI_license_no": "bpp_providers.items.time_to_ship",
//                   "imported_product_country_of_origin": "bpp_providers.items.time_to_ship"
//                 },
//                 "@ondc/org/mandatory_reqs_veggies_fruits": {
//                   "net_quantity": "bpp_providers.items.time_to_ship"
//                 },
//               }
//             ],
//             "fulfillments": [{
//               "contact": "bpp_providers.fulfillments.contact"
//             }
//             ],

//             "tags": [
//               {
//                 "list": "bpp_providers.tags.list"
//               }
//             ]
//           }
//         ],
//         "bpp_fulfillments": "bpp_fulfillments",
//       },
//       async function (data, err) {
//         // console.log(JSON.stringify(data),err)
//       },
//     )
//   })